import React, { useState } from 'react';
import { FileText, Copy, Check, DownloadSimple, X } from '@phosphor-icons/react';
import { Scenario, Incident, SystemNode, SystemEdge } from '../types';
import { IncidentMaxHeap, calculateIncidentScore } from '../algorithms/priorityQueue';
import { runKahnsTopologicalSort, runBFSBlastRadius } from '../algorithms/graphTraversal';
import { runDijkstraContainmentPath } from '../algorithms/shortestPath';

interface AuditReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  scenario: Scenario;
  nodes: SystemNode[];
  edges: SystemEdge[];
  incidents: Incident[];
}

export const AuditReportModal: React.FC<AuditReportModalProps> = ({
  isOpen,
  onClose,
  scenario,
  nodes,
  edges,
  incidents
}) => {
  const [copied, setCopied] = useState<boolean>(false);

  if (!isOpen) return null;

  // Run algorithms to populate report data
  const nodeMap = new Map(nodes.map(n => [n.id, n]));
  const heap = new IncidentMaxHeap();
  incidents.forEach(inc => {
    const n = nodeMap.get(inc.targetNodeId);
    if (!n) return;
    const { score, breakdown, cascadingImpact } = calculateIncidentScore(inc, n, edges);
    heap.insert({
      incident: inc,
      score,
      nodeName: n.name,
      criticality: n.criticality,
      cascadingImpact,
      formulaBreakdown: breakdown
    });
  });

  const kahn = runKahnsTopologicalSort(nodes, edges);
  const compIds = incidents.map(i => i.targetNodeId);
  const bfs = runBFSBlastRadius(compIds.slice(0, 1), nodes, edges);
  const dijkstra = nodes.length >= 2 ? runDijkstraContainmentPath(nodes[0].id, nodes[nodes.length - 1].id, nodes, edges) : null;

  const reportMarkdown = `# CYBER INCIDENT CONTAINMENT PLAYBOOK & AUDIT REPORT
Generated by: CyberCPR DAA Cyber Incident Response Planner
Compliance Framework: NIST SP 800-61 Rev. 2 / CERT-In Directions 2022
Date: ${new Date().toISOString()}

## 1. EXECUTIVE SUMMARY
- Target Infrastructure: ${scenario.name}
- Industry Domain: ${scenario.industry}
- Identified Threat Actor: ${scenario.threatActor}
- Total Monitored Nodes: ${nodes.length}
- Active Breaches Detected: ${incidents.length}
- System Dependency Status: ${kahn.hasCycle ? "CYCLE DETECTED (Deadlock)" : "Valid DAG Verified"}

## 2. PRIORITY QUEUE DISPATCH SCHEDULE (BINARY MAX-HEAP)
Rule: Evaluates multi-criteria priority function balancing CVSS severity, asset business criticality, cascading dependent count, and regulatory SLA time.

${heap.getHeapArray().map((item, idx) => `### Priority #${idx + 1}: ${item.incident.title}
- Target Host: ${item.nodeName} (${item.incident.targetNodeId})
- Calculated Score: ${item.score}
- CVSS Severity: ${item.incident.cvss} (${item.incident.severity})
- Host Criticality: ${item.criticality} / 10
- Downstream Dependent Services: ${item.cascadingImpact}
- CERT-In / SLA Threshold: ${item.incident.slaLimitMinutes} minutes
`).join('\n')}

## 3. DEPENDENCY-SAFE CONTAINMENT SEQUENCING (KAHN'S ALGORITHM)
To prevent service collapse and operational blackout, containment actions must follow the topological drain sequence:
${kahn.order.map((id, idx) => `${idx + 1}. [${nodeMap.get(id)?.name}] (${nodeMap.get(id)?.ip}) - Subnet: ${nodeMap.get(id)?.subnet}`).join('\n')}

## 4. BLAST RADIUS & CONTAINMENT CUT BOUNDARY (BFS & DIJKSTRA)
- Perimeter Isolation Lines Identified: ${bfs.containmentPerimeterEdgeIds.length} strategic network segment cut lines.
- Optimal Containment Route: ${dijkstra ? dijkstra.pathNames.join(' -> ') : 'N/A'}
- Minimum Operational Disruption Score: ${dijkstra ? dijkstra.totalCost : 0} points
- Severed Isolation Edges: ${dijkstra ? dijkstra.edgesCut.join(', ') : 'None'}

## 5. STATUTORY COMPLIANCE & LEGAL NOTICE
- India CERT-In Directions 2022: Critical cyber security incidents must be reported to CERT-In within 6 hours of discovery.
- Digital Personal Data Protection (DPDP) Act 2023: Affected entities must deploy technical safeguards to protect personally identifiable records and minimize data loss.
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(reportMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([reportMarkdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `incident_containment_playbook_${Date.now()}.md`;
    a.click();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fadeIn">
      <div className="relative w-full max-w-3xl max-h-[90vh] rounded-2xl border border-[#CDBFA7] bg-[#FAF6EE] text-[#3F0D1B] flex flex-col shadow-2xl overflow-hidden transition-colors">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-[#CDBFA7] bg-[#EDE4D6]">
          <div className="flex items-center gap-2">
            <FileText size={22} className="text-[#3F0D1B]" />
            <div>
              <h2 className="text-base font-bold text-[#3F0D1B] tracking-tight">
                Incident Response Playbook & Audit Report
              </h2>
              <span className="text-[11px] font-mono text-[#521A27]">
                NIST SP 800-61 Rev 2 & CERT-In 6-Hour Reporting Standard
              </span>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#FAF6EE] hover:bg-[#EDE4D6] text-[#3F0D1B] border border-[#CDBFA7] text-xs font-semibold transition-colors shadow-xs"
            >
              {copied ? <Check size={14} className="text-[#3F0D1B]" /> : <Copy size={14} />}
              <span>{copied ? 'Copied' : 'Copy MD'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-[#3F0D1B] hover:bg-[#5C1D2D] text-[#FAF6EE] text-xs font-bold transition-all shadow-md shadow-[#3F0D1B]/20"
            >
              <DownloadSimple size={14} weight="bold" />
              <span>Download</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-[#521A27] hover:text-[#3F0D1B] hover:bg-[#EDE4D6] transition-colors ml-1"
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Content Body */}
        <div className="flex-1 overflow-y-auto p-5 font-mono text-xs text-[#3F0D1B] leading-relaxed bg-[#FAF6EE] whitespace-pre-wrap selection:bg-[#3F0D1B]/20">
          {reportMarkdown}
        </div>
      </div>
    </div>
  );
};
